I'm sorry, but an uncaught exception occurred.

After initialization, but before game start.
  File "game/screens.rpy", line 594, in prepare_screen
    screen save():
  File "game/screens.rpy", line 594, in prepare
    screen save():
Exception: A screen named file_slots does not exist.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\Schoolworks\Bathspa\CC Year 3 (sem 2)\Creative Incubator\Renpy\renpy-8.3.7-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "D:\Schoolworks\Bathspa\CC Year 3 (sem 2)\Creative Incubator\Renpy\renpy-8.3.7-sdk\renpy\main.py", line 652, in main
    run(restart)
  File "D:\Schoolworks\Bathspa\CC Year 3 (sem 2)\Creative Incubator\Renpy\renpy-8.3.7-sdk\renpy\main.py", line 94, in run
    renpy.display.screen.prepare_screens()
  File "D:\Schoolworks\Bathspa\CC Year 3 (sem 2)\Creative Incubator\Renpy\renpy-8.3.7-sdk\renpy\display\screen.py", line 1027, in prepare_screens
    s.ast.prepare_screen()
  File "game/screens.rpy", line 594, in prepare_screen
    screen save():
  File "game/screens.rpy", line 594, in prepare
    screen save():
  File "D:\Schoolworks\Bathspa\CC Year 3 (sem 2)\Creative Incubator\Renpy\renpy-8.3.7-sdk\renpy\sl2\slast.py", line 2030, in prepare
    raise Exception("A screen named {} does not exist.".format(self.target))
Exception: A screen named file_slots does not exist.

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.7.25031702
The Last Toast 1.0
Wed Apr 30 20:18:45 2025
