I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1761, in script
    scene bg trnolight with fadein
  File "game/script.rpy", line 1761, in <module>
    scene bg trnolight with fadein
NameError: name 'fadein' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1761, in script
    scene bg trnolight with fadein
  File "D:\Schoolworks\Bathspa\CC Year 3 (sem 2)\Creative Incubator\Renpy\renpy-8.3.7-sdk\renpy\ast.py", line 1370, in execute
    paired = renpy.python.py_eval(self.paired)
  File "D:\Schoolworks\Bathspa\CC Year 3 (sem 2)\Creative Incubator\Renpy\renpy-8.3.7-sdk\renpy\python.py", line 1218, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\Schoolworks\Bathspa\CC Year 3 (sem 2)\Creative Incubator\Renpy\renpy-8.3.7-sdk\renpy\python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 1761, in <module>
    scene bg trnolight with fadein
NameError: name 'fadein' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.7.25031702
The Last Toast 1.0
Tue May 20 18:07:01 2025
